version: '3.8'

services:
  api:
    container_name: nestjs_api
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/database
      - JWT_SECRET=yourSecretKey
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=songmanageruser
      - MYSQL_PASSWORD=songmanageruserpassword
      - MYSQL_ROOT_PASSWORD=password
      - ASIA/TOKYO
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql_data:
  prisma-volumn: